
-- require("zk").setup({
--   -- can be "telescope", "fzf" or "select" (`vim.ui.select`)
--   -- it's recommended to use "telescope" or "fzf"
--   picker = "telescope",
--
--   lsp = {
--     -- `config` is passed to `vim.lsp.start_client(config)`
--     config = {
--       cmd = { "zk", "lsp" },
--       name = "zk",
--       -- on_attach = ...
--       -- etc, see `:h vim.lsp.start_client()`
--     },
--
--     -- automatically attach buffers in a zk notebook that match the given filetypes
--     auto_attach = {
--       enabled = true,
--       filetypes = { "markdown" },
--     },
--   },
-- })
--
--
-- local wk = require("which-key")
--
--
-- wk.register({
--     z = {
--         name = "Zettelkasten",
--         n = { "<Cmd>ZkNew { title = vim.fn.input('Title: ')}<CR>", "New note"},
--         f = { "<Cmd>ZkNotes { sort = {'modified'} }<CR>", "Open note"},
--         t = { "<Cmd>ZkTags<CR>", "Open note (tags)"},
--     },
--
-- }, { noremap=true, silent=false , prefix="<leader>"})
--
-- wk.register({
--     z = {
--         name = "Zettelkasten",
--         f = { ":'<,'>ZkMatch<CR>", "Search for selection"}
--     },
--
-- }, { noremap=true, silent=false , prefix="<leader>", mode="v"})
